### PR TITLE
Initial commit of project template

### PR DESCRIPTION
**Pull request by JoshuaGRubin**
All I've done here is uploaded Matt Rubashkin's Insight project template.

### CODE REVIEW

**Comment by mstefferson** [comment]
For now, feel free to submit a PR (just like you did) and just merge it in. Don't let me slow you down. We'll talk about the workflow on this tomorrow.

**Comment by JoshuaGRubin** [comment]
Sounds good.  Thanks for noticing the additions.  It's occurring to me that commits are building on other commits, so a lot of commits turn into branches on branches for the moment.  Looking forward to syncing on workflow!

**Comment by mstefferson** [comment]
Hmmm. I'm a little confused by this. Yes, commits should always be building on other commits. You don't need to make a new branch for every commit. A branch should contain a new feature or fix to the code and could be anywhere from 1-20 commits

**Comment by JoshuaGRubin** [comment]
Right - makes sense.  No stranger to git, but new to pull requests.  So to add a new feature using something pending in a pull request that hasn't been approved and merged into the master branch, I can't branch off the master for the new feature since it needs the unapproved stuff => hence the (admittedly) odd branch-off-the-branch concept.  We can definitely resolve this tomorrow; it's just workflow.

**Comment by mstefferson** [comment]
Ah ya. I see now. I was also new the PR game when I started insight. You'll get the hang in no time. For now, just merge all branches straight into master

**Pull request merged**
